steps:
- name: 'gcr.io/cloud-builders/docker'
  dir: 'data-mapping-poc/job-runner'
  args: [ 'build', '-t', '$_REGION_-docker.pkg.dev/$_PROJECT_ID_/job-runner/job-runner', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', '$_REGION_-docker.pkg.dev/$_PROJECT_ID_/job-runner/job-runner']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'job-runner', '--image', '$_REGION_-docker.pkg.dev/$_PROJECT_ID_/job-runner/job-runner', '--region', '$_REGION_']
images:
- $_REGION_-docker.pkg.dev/$_PROJECT_ID_/job-runner/job-runner